language: c++

env:
 global:

before_install:

install:
    - sudo apt-get install libx32gcc-4.8-dev
    - sudo apt-get install libc6-dev-i386
    - wget http://dl.google.com/android/ndk/android-ndk-r8c-linux-x86.tar.bz2
    - tar jxf android-ndk-r8c-linux-x86.tar.bz2
    - export ANDROID_NDK=${PWD}/android-ndk-r8c
    
script: 
    - ./build_v8.sh

after_success:
