language: c++

env:
 global:

before_install:

install:
    - wget http://dl.google.com/android/ndk/android-ndk-r8c-linux-x86.tar.bz2
    - tar vjxf android-ndk-r8c-linux-x86.tar.bz2
    - export ANDROID_NDK=${PWD}/android-ndk-r8c
    
script: 
    - ./build_v8.sh

after_success:
